#[cfg(feature = "dim2")]
pub mod rapier_damped_spring_joint_2d;
#[cfg(feature = "dim2")]
pub mod rapier_groove_joint_2d;
pub mod rapier_joint;
#[cfg(feature = "dim2")]
pub mod rapier_pin_joint_2d;
#[cfg(feature = "dim3")]
pub mod rapier_pin_joint_3d;
