pub mod rapier_capsule_shape;
pub mod rapier_circle_shape;
pub mod rapier_concave_polygon_shape;
pub mod rapier_convex_polygon_shape;
#[cfg(feature = "dim3")]
pub mod rapier_cylinder_shape_3d;
#[cfg(feature = "dim3")]
pub mod rapier_heightmap_shape_3d;
pub mod rapier_rectangle_shape;
#[cfg(feature = "dim2")]
pub mod rapier_segment_shape_2d;
pub mod rapier_separation_ray_shape;
pub mod rapier_shape;
pub mod rapier_world_boundary_shape;
