name: Release
on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      # dynamic
      - name: Download artifacts 2d
        uses: actions/download-artifact@v7
        with:
          pattern: godot-rapier-2d-single-*
          merge-multiple: true
          path: godot-rapier-2d-single
          name: godot-rapier-2d-single
      - name: Download artifacts 3d
        uses: actions/download-artifact@v7
        with:
          pattern: godot-rapier-3d-single-*
          merge-multiple: true
          path: godot-rapier-3d-single
          name: godot-rapier-3d-single
      # static
      - name: Download artifacts 2d static
        uses: actions/download-artifact@v7
        with:
          pattern: static-rapier-2d-single-*
          merge-multiple: true
          path: static-rapier-2d-single
          name: static-rapier-2d-single
      - name: Download artifacts 3d static
        uses: actions/download-artifact@v7
        with:
          pattern: static-rapier-3d-single-*
          merge-multiple: true
          path: static-rapier-3d-single
          name: static-rapier-3d-single
      - name: Delete draft release(s)
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive
        shell: sh
        run: |
          ls
          # dynamic
          zip -r "godot-rapier-2d-single.zip" godot-rapier-2d-single
          zip -r "godot-rapier-3d-single.zip" godot-rapier-3d-single
          # static
          zip -r "static-rapier-2d-single.zip" static-rapier-2d-single
          zip -r "static-rapier-3d-single.zip" static-rapier-3d-single
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Godot Rapier Nightly
          files: |
            godot-rapier-2d-single.zip
            godot-rapier-3d-single.zip
            static-rapier-2d-single.zip
            static-rapier-3d-single.zip
          generate_release_notes: true
          draft: true
          prerelease: true
          fail_on_unmatched_files: true
